site_name: Battery Emulator
site_description: Documentation (Wiki) for Battery Emulator
site_url: https://nagyrobi.github.io/Battery-Emulator-Docs
repo_name: 'dalathegreat/Battery-Emulator'
repo_url: 'https://github.com/dalathegreat/Battery-Emulator'
edit_uri: 'https://github.com/nagyrobi/Battery-Emulator-Docs/blob/master/docs/'
docs_dir: docs
theme:
  name: material
  logo: assets/be.svg
  favicon: assets/be.ico
  language: 'en'
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light green
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
#    - navigation.tracking
#    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.action.edit
    - content.code.copy
  icon:
    admonition:
      note: octicons/tag-16
      info: octicons/info-16
      warning: octicons/alert-16
      danger: octicons/zap-16
  font:
#    text: Barlow
    code: Roboto Mono
extra:
  social:
    - icon: fontawesome/brands/patreon
      link: 'https://www.patreon.com/dala'
    - icon: fontawesome/brands/github
      link: 'https://github.com/dalathegreat/Battery-Emulator'
markdown_extensions:
  - admonition
  - toc:
     permalink: "~"
     toc_depth: 4
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
#  - def_list
#  - attr_list
#  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
#  - minify:
#      minify_html: true
#  - offline
  - search:
      lang:
        - en
  - awesome-nav
  - redirects:
      redirect_maps:
          'bmsreset.md': '40-setup/10-hardware/Periodic-BMS-reset.md'
#          'old/file.md': 'new/file.md'
#          'some_file.md': 'http://external.url.com/foobar'
