site_name: Battery Emulator
site_url: https://nagyrobi.github.io/Battery-Emulator-Docs
theme:
  name: material
  language: 'en'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - content.action.edit
    - content.code.copy
  font:
    text: Barlow
    code: Roboto Mono
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/dalathegreat/Battery-Emulator'
plugins:
  - offline
  - search:
      lang:
        - en
  - minify:
      minify_html: true
markdown_extensions:
  - admonition
  - toc:
     permalink: "~"
     toc_depth: 3
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.tilde
  - meta
  - def_list
  - attr_list
  - md_in_html
nav:
  - Help:
    - Patreon: https://www.patreon.com/dala "target=_blank"
  - Web Installer: "https://dalathegreat.github.io/BE-Web-Installer/"
