nav:
  - Home: index.md
  - Documentation: documentation
  - Inverters: supported-inverters
  - Batteries: supported-batteries
  - Hardware: supported-emulator-hardware
  - "*"
  - Web Installer: https://dalathegreat.github.io/BE-Web-Installer/ "target=_blank"